name: Graphtik

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[all]
      - name: Test
        run: |
          # Undo configs in setup.cfg
          echo -e '[pytest]\nmarkers: slow' > pytest.ini
          pytest --cov=graphtik #--log-level=DEBUG -v
      - name: Upload@Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
      - name: Site
        run: |
          python setup.py build_sphinx
      - name: Wheel
        run: |
          python setup.py bdist_wheel
      - name: Sources
        run: |
          python setup.py sdist
